version: 0.1

phases:
  install:
    commands:
      - apt-get install ruby-full
      - echo Installing RSpec...
      - gem install rspec
      - echo ruby --version
  build:
    commands:
      - echo Build started on `date`
      - echo Compiling the Ruby code...
      - rspec HelloWorld_spec.rb
  post_build:
    commands:
      - echo Build completed on `date`
artifacts:
  files:
    - HelloWorld.rb

